/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 3
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  aux_sym_section_header_token1 = 2,
  anon_sym_RBRACK = 3,
  sym_comment = 4,
  anon_sym_EQ = 5,
  anon_sym_COMMA = 6,
  sym_directive = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_no_DASHresolve = 10,
  anon_sym_force_DASHremote_DASHdns = 11,
  anon_sym_pre_DASHmatching = 12,
  anon_sym_extended_DASHmatching = 13,
  anon_sym_dns_DASHfailed = 14,
  sym__word = 15,
  sym__newline = 16,
  sym_source_file = 17,
  sym_section = 18,
  sym_section_header = 19,
  sym__line = 20,
  sym_setting = 21,
  sym_value_list = 22,
  sym__item = 23,
  sym_parameter = 24,
  sym_rule = 25,
  sym__rule_arg = 26,
  sym_group = 27,
  sym_nested_rule = 28,
  sym_rule_modifier = 29,
  sym_raw_line = 30,
  sym_value = 31,
  sym_policy = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_source_file_repeat2 = 34,
  aux_sym_value_list_repeat1 = 35,
  aux_sym_rule_repeat1 = 36,
  aux_sym_rule_repeat2 = 37,
  aux_sym_group_repeat1 = 38,
  aux_sym_nested_rule_repeat1 = 39,
  alias_sym_key = 40,
  alias_sym_param_name = 41,
  alias_sym_rule_type = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [aux_sym_section_header_token1] = "section_name",
  [anon_sym_RBRACK] = "]",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [sym_directive] = "directive",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_no_DASHresolve] = "no-resolve",
  [anon_sym_force_DASHremote_DASHdns] = "force-remote-dns",
  [anon_sym_pre_DASHmatching] = "pre-matching",
  [anon_sym_extended_DASHmatching] = "extended-matching",
  [anon_sym_dns_DASHfailed] = "dns-failed",
  [sym__word] = "_word",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_section] = "section",
  [sym_section_header] = "section_header",
  [sym__line] = "_line",
  [sym_setting] = "setting",
  [sym_value_list] = "value_list",
  [sym__item] = "_item",
  [sym_parameter] = "parameter",
  [sym_rule] = "rule",
  [sym__rule_arg] = "_rule_arg",
  [sym_group] = "group",
  [sym_nested_rule] = "nested_rule",
  [sym_rule_modifier] = "rule_modifier",
  [sym_raw_line] = "raw_line",
  [sym_value] = "value",
  [sym_policy] = "policy",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_value_list_repeat1] = "value_list_repeat1",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym_rule_repeat2] = "rule_repeat2",
  [aux_sym_group_repeat1] = "group_repeat1",
  [aux_sym_nested_rule_repeat1] = "nested_rule_repeat1",
  [alias_sym_key] = "key",
  [alias_sym_param_name] = "param_name",
  [alias_sym_rule_type] = "rule_type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_section_header_token1] = aux_sym_section_header_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_directive] = sym_directive,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_no_DASHresolve] = anon_sym_no_DASHresolve,
  [anon_sym_force_DASHremote_DASHdns] = anon_sym_force_DASHremote_DASHdns,
  [anon_sym_pre_DASHmatching] = anon_sym_pre_DASHmatching,
  [anon_sym_extended_DASHmatching] = anon_sym_extended_DASHmatching,
  [anon_sym_dns_DASHfailed] = anon_sym_dns_DASHfailed,
  [sym__word] = sym__word,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_section] = sym_section,
  [sym_section_header] = sym_section_header,
  [sym__line] = sym__line,
  [sym_setting] = sym_setting,
  [sym_value_list] = sym_value_list,
  [sym__item] = sym__item,
  [sym_parameter] = sym_parameter,
  [sym_rule] = sym_rule,
  [sym__rule_arg] = sym__rule_arg,
  [sym_group] = sym_group,
  [sym_nested_rule] = sym_nested_rule,
  [sym_rule_modifier] = sym_rule_modifier,
  [sym_raw_line] = sym_raw_line,
  [sym_value] = sym_value,
  [sym_policy] = sym_policy,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_value_list_repeat1] = aux_sym_value_list_repeat1,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym_rule_repeat2] = aux_sym_rule_repeat2,
  [aux_sym_group_repeat1] = aux_sym_group_repeat1,
  [aux_sym_nested_rule_repeat1] = aux_sym_nested_rule_repeat1,
  [alias_sym_key] = alias_sym_key,
  [alias_sym_param_name] = alias_sym_param_name,
  [alias_sym_rule_type] = alias_sym_rule_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_header_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no_DASHresolve] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_force_DASHremote_DASHdns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pre_DASHmatching] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extended_DASHmatching] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dns_DASHfailed] = {
    .visible = true,
    .named = false,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_value_list] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__rule_arg] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_line] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_policy] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nested_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_key] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_rule_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_policy = 2,
  field_type = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_policy] = "policy",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_policy, 2},
    {field_type, 0},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_policy, 3},
    {field_type, 0},
  [7] =
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_key,
  },
  [2] = {
    [0] = alias_sym_param_name,
  },
  [3] = {
    [0] = alias_sym_rule_type,
  },
  [4] = {
    [0] = alias_sym_param_name,
  },
  [5] = {
    [0] = alias_sym_rule_type,
  },
  [6] = {
    [1] = alias_sym_rule_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
};

static const TSCharacterRange sym__word_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '\''}, {'*', '+'}, {'-', ':'}, {'<', '<'}, {'>', 'Z'},
  {'\\', '\\'}, {'^', 0x17e}, {0x180, 0x2129}, {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(68);
      ADVANCE_MAP(
        '\n', 87,
        '\r', 1,
        '%', 66,
        '(', 77,
        ')', 78,
        ',', 75,
        '=', 74,
        '[', 69,
        ']', 72,
        'd', 42,
        'e', 63,
        'f', 48,
        'n', 47,
        'p', 51,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(73);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(87);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '%') ADVANCE(85);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if ((!eof && set_contains(sym__word_character_set_1, 12, lookahead))) ADVANCE(86);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(53);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(54);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(41);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(61);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(83);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 29:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(81);
      END_STATE();
    case 31:
      if (lookahead == 'g') ADVANCE(82);
      END_STATE();
    case 32:
      if (lookahead == 'h') ADVANCE(35);
      END_STATE();
    case 33:
      if (lookahead == 'h') ADVANCE(36);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 40:
      if (lookahead == 'm') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 50:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 55:
      if (lookahead == 's') ADVANCE(80);
      END_STATE();
    case 56:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 57:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 62:
      if (lookahead == 'v') ADVANCE(20);
      END_STATE();
    case 63:
      if (lookahead == 'x') ADVANCE(58);
      END_STATE();
    case 64:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 65:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 66:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 67:
      if (eof) ADVANCE(68);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(77);
      if (lookahead == ',') ADVANCE(75);
      if (lookahead == '[') ADVANCE(69);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(67);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '=' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_section_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_section_header_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_directive);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_no_DASHresolve);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_force_DASHremote_DASHdns);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_pre_DASHmatching);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_extended_DASHmatching);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_dns_DASHfailed);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '%') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 67},
  [2] = {.lex_state = 67},
  [3] = {.lex_state = 67},
  [4] = {.lex_state = 67},
  [5] = {.lex_state = 67},
  [6] = {.lex_state = 67},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 67},
  [9] = {.lex_state = 67},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 67},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 67},
  [16] = {.lex_state = 67},
  [17] = {.lex_state = 67},
  [18] = {.lex_state = 67},
  [19] = {.lex_state = 67},
  [20] = {.lex_state = 67},
  [21] = {.lex_state = 67},
  [22] = {.lex_state = 67},
  [23] = {.lex_state = 67},
  [24] = {.lex_state = 67},
  [25] = {.lex_state = 67},
  [26] = {.lex_state = 67},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 67},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 67},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 64},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_directive] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_no_DASHresolve] = ACTIONS(1),
    [anon_sym_force_DASHremote_DASHdns] = ACTIONS(1),
    [anon_sym_pre_DASHmatching] = ACTIONS(1),
    [anon_sym_extended_DASHmatching] = ACTIONS(1),
    [anon_sym_dns_DASHfailed] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym_section] = STATE(11),
    [sym_section_header] = STATE(3),
    [sym__line] = STATE(2),
    [sym_setting] = STATE(2),
    [sym_rule] = STATE(2),
    [sym_raw_line] = STATE(2),
    [sym_value] = STATE(64),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym__word] = ACTIONS(9),
    [sym__newline] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym__word,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_section_header,
    STATE(64), 1,
      sym_value,
    ACTIONS(13), 2,
      sym_comment,
      sym__newline,
    STATE(13), 2,
      sym_section,
      aux_sym_source_file_repeat2,
    STATE(5), 5,
      sym__line,
      sym_setting,
      sym_rule,
      sym_raw_line,
      aux_sym_source_file_repeat1,
  [31] = 5,
    ACTIONS(9), 1,
      sym__word,
    STATE(64), 1,
      sym_value,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(17), 2,
      sym_comment,
      sym__newline,
    STATE(4), 5,
      sym__line,
      sym_setting,
      sym_rule,
      sym_raw_line,
      aux_sym_source_file_repeat1,
  [53] = 5,
    ACTIONS(9), 1,
      sym__word,
    STATE(64), 1,
      sym_value,
    ACTIONS(13), 2,
      sym_comment,
      sym__newline,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(5), 5,
      sym__line,
      sym_setting,
      sym_rule,
      sym_raw_line,
      aux_sym_source_file_repeat1,
  [75] = 5,
    ACTIONS(26), 1,
      sym__word,
    STATE(64), 1,
      sym_value,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(23), 2,
      sym_comment,
      sym__newline,
    STATE(5), 5,
      sym__line,
      sym_setting,
      sym_rule,
      sym_raw_line,
      aux_sym_source_file_repeat1,
  [97] = 5,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym__word,
    STATE(8), 1,
      aux_sym_rule_repeat1,
    STATE(43), 1,
      sym_policy,
    STATE(68), 3,
      sym__rule_arg,
      sym_group,
      sym_value,
  [115] = 5,
    ACTIONS(33), 1,
      sym_directive,
    ACTIONS(35), 1,
      sym__word,
    ACTIONS(37), 1,
      sym__newline,
    STATE(66), 1,
      sym_value_list,
    STATE(41), 3,
      sym__item,
      sym_parameter,
      sym_value,
  [133] = 5,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym__word,
    STATE(9), 1,
      aux_sym_rule_repeat1,
    STATE(35), 1,
      sym_policy,
    STATE(68), 3,
      sym__rule_arg,
      sym_group,
      sym_value,
  [151] = 4,
    ACTIONS(39), 1,
      anon_sym_LPAREN,
    ACTIONS(42), 1,
      sym__word,
    STATE(9), 1,
      aux_sym_rule_repeat1,
    STATE(68), 3,
      sym__rule_arg,
      sym_group,
      sym_value,
  [166] = 2,
    STATE(55), 1,
      sym_rule_modifier,
    ACTIONS(45), 5,
      anon_sym_no_DASHresolve,
      anon_sym_force_DASHremote_DASHdns,
      anon_sym_pre_DASHmatching,
      anon_sym_extended_DASHmatching,
      anon_sym_dns_DASHfailed,
  [177] = 4,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_section_header,
    STATE(14), 2,
      sym_section,
      aux_sym_source_file_repeat2,
  [191] = 1,
    ACTIONS(47), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [199] = 4,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_section_header,
    STATE(14), 2,
      sym_section,
      aux_sym_source_file_repeat2,
  [213] = 4,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    STATE(3), 1,
      sym_section_header,
    STATE(14), 2,
      sym_section,
      aux_sym_source_file_repeat2,
  [227] = 1,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [235] = 1,
    ACTIONS(58), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [243] = 1,
    ACTIONS(60), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [251] = 1,
    ACTIONS(62), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [259] = 1,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [267] = 1,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [275] = 3,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 1,
      sym__word,
    STATE(40), 3,
      sym__rule_arg,
      sym_group,
      sym_value,
  [287] = 1,
    ACTIONS(70), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_comment,
      sym__word,
      sym__newline,
  [295] = 3,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(68), 1,
      sym__word,
    STATE(58), 3,
      sym__rule_arg,
      sym_group,
      sym_value,
  [307] = 2,
    ACTIONS(72), 1,
      sym__word,
    STATE(28), 3,
      sym__item,
      sym_parameter,
      sym_value,
  [316] = 3,
    ACTIONS(68), 1,
      sym__word,
    STATE(46), 1,
      sym_value,
    ACTIONS(74), 2,
      anon_sym_COMMA,
      sym__newline,
  [327] = 2,
    ACTIONS(72), 1,
      sym__word,
    STATE(48), 3,
      sym__item,
      sym_parameter,
      sym_value,
  [336] = 3,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      aux_sym_group_repeat1,
  [346] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      sym__newline,
    STATE(36), 1,
      aux_sym_value_list_repeat1,
  [356] = 3,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      sym__newline,
  [366] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      sym__newline,
    STATE(34), 1,
      aux_sym_value_list_repeat1,
  [376] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      aux_sym_group_repeat1,
  [386] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      sym__newline,
    STATE(42), 1,
      aux_sym_rule_repeat2,
  [396] = 2,
    ACTIONS(99), 1,
      anon_sym_EQ,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      sym__newline,
  [404] = 3,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(104), 1,
      sym__newline,
    STATE(34), 1,
      aux_sym_value_list_repeat1,
  [414] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(106), 1,
      sym__newline,
    STATE(44), 1,
      aux_sym_rule_repeat2,
  [424] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(108), 1,
      sym__newline,
    STATE(34), 1,
      aux_sym_value_list_repeat1,
  [434] = 1,
    ACTIONS(89), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__newline,
  [440] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      aux_sym_group_repeat1,
  [450] = 3,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_nested_rule_repeat1,
  [460] = 3,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_nested_rule_repeat1,
  [470] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      sym__newline,
    STATE(30), 1,
      aux_sym_value_list_repeat1,
  [480] = 3,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(123), 1,
      sym__newline,
    STATE(42), 1,
      aux_sym_rule_repeat2,
  [490] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      sym__newline,
    STATE(32), 1,
      aux_sym_rule_repeat2,
  [500] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      sym__newline,
    STATE(42), 1,
      aux_sym_rule_repeat2,
  [510] = 3,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_nested_rule_repeat1,
  [520] = 1,
    ACTIONS(134), 2,
      anon_sym_COMMA,
      sym__newline,
  [525] = 1,
    ACTIONS(136), 2,
      anon_sym_LPAREN,
      sym__word,
  [530] = 1,
    ACTIONS(104), 2,
      anon_sym_COMMA,
      sym__newline,
  [535] = 2,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    STATE(54), 1,
      sym_nested_rule,
  [542] = 1,
    ACTIONS(140), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [547] = 2,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      sym__newline,
  [554] = 2,
    ACTIONS(138), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_nested_rule,
  [561] = 1,
    ACTIONS(147), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [566] = 1,
    ACTIONS(79), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [571] = 1,
    ACTIONS(123), 2,
      anon_sym_COMMA,
      sym__newline,
  [576] = 1,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [581] = 1,
    ACTIONS(151), 2,
      anon_sym_COMMA,
      sym__newline,
  [586] = 1,
    ACTIONS(132), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [591] = 1,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [596] = 1,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
  [600] = 1,
    ACTIONS(157), 1,
      sym__word,
  [604] = 1,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
  [608] = 1,
    ACTIONS(161), 1,
      aux_sym_section_header_token1,
  [612] = 1,
    ACTIONS(163), 1,
      sym__newline,
  [616] = 1,
    ACTIONS(165), 1,
      sym__newline,
  [620] = 1,
    ACTIONS(167), 1,
      sym__newline,
  [624] = 1,
    ACTIONS(169), 1,
      anon_sym_COMMA,
  [628] = 1,
    ACTIONS(171), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 53,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 97,
  [SMALL_STATE(7)] = 115,
  [SMALL_STATE(8)] = 133,
  [SMALL_STATE(9)] = 151,
  [SMALL_STATE(10)] = 166,
  [SMALL_STATE(11)] = 177,
  [SMALL_STATE(12)] = 191,
  [SMALL_STATE(13)] = 199,
  [SMALL_STATE(14)] = 213,
  [SMALL_STATE(15)] = 227,
  [SMALL_STATE(16)] = 235,
  [SMALL_STATE(17)] = 243,
  [SMALL_STATE(18)] = 251,
  [SMALL_STATE(19)] = 259,
  [SMALL_STATE(20)] = 267,
  [SMALL_STATE(21)] = 275,
  [SMALL_STATE(22)] = 287,
  [SMALL_STATE(23)] = 295,
  [SMALL_STATE(24)] = 307,
  [SMALL_STATE(25)] = 316,
  [SMALL_STATE(26)] = 327,
  [SMALL_STATE(27)] = 336,
  [SMALL_STATE(28)] = 346,
  [SMALL_STATE(29)] = 356,
  [SMALL_STATE(30)] = 366,
  [SMALL_STATE(31)] = 376,
  [SMALL_STATE(32)] = 386,
  [SMALL_STATE(33)] = 396,
  [SMALL_STATE(34)] = 404,
  [SMALL_STATE(35)] = 414,
  [SMALL_STATE(36)] = 424,
  [SMALL_STATE(37)] = 434,
  [SMALL_STATE(38)] = 440,
  [SMALL_STATE(39)] = 450,
  [SMALL_STATE(40)] = 460,
  [SMALL_STATE(41)] = 470,
  [SMALL_STATE(42)] = 480,
  [SMALL_STATE(43)] = 490,
  [SMALL_STATE(44)] = 500,
  [SMALL_STATE(45)] = 510,
  [SMALL_STATE(46)] = 520,
  [SMALL_STATE(47)] = 525,
  [SMALL_STATE(48)] = 530,
  [SMALL_STATE(49)] = 535,
  [SMALL_STATE(50)] = 542,
  [SMALL_STATE(51)] = 547,
  [SMALL_STATE(52)] = 554,
  [SMALL_STATE(53)] = 561,
  [SMALL_STATE(54)] = 566,
  [SMALL_STATE(55)] = 571,
  [SMALL_STATE(56)] = 576,
  [SMALL_STATE(57)] = 581,
  [SMALL_STATE(58)] = 586,
  [SMALL_STATE(59)] = 591,
  [SMALL_STATE(60)] = 596,
  [SMALL_STATE(61)] = 600,
  [SMALL_STATE(62)] = 604,
  [SMALL_STATE(63)] = 608,
  [SMALL_STATE(64)] = 612,
  [SMALL_STATE(65)] = 616,
  [SMALL_STATE(66)] = 620,
  [SMALL_STATE(67)] = 624,
  [SMALL_STATE(68)] = 628,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_line, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(63),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 4, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 3),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 4, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 3),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 6, 0, 5),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 2),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 1, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat2, 2, 0, 0), SHIFT_REPEAT(10),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat2, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_nested_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nested_rule_repeat1, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 1, 0, 0), REDUCE(sym_policy, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_policy, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_rule, 5, 0, 6),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_modifier, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_rule, 6, 0, 6),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [159] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_surge(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "surge",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
